/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosSurfacesRouteImport } from './routes/demos/surfaces'
import { Route as DemosScrollableBasicRouteImport } from './routes/demos/scrollable-basic'
import { Route as DemosMotionBasicRouteImport } from './routes/demos/motion-basic'
import { Route as DemosInputRouteImport } from './routes/demos/input'
import { Route as DemosDraggableBasicRouteImport } from './routes/demos/draggable-basic'
import { Route as DemosCarouselRouteImport } from './routes/demos/carousel'
import { Route as DemosA11yRouteImport } from './routes/demos/a11y'
import { Route as DemosScreenTransitionRouteImport } from './routes/demos/screen/transition'
import { Route as DemosScreenEffectStackRouteImport } from './routes/demos/screen/effect-stack'
import { Route as DemosRendererQuadRenderingRouteImport } from './routes/demos/renderer/quad-rendering'
import { Route as DemosRendererMultiEffectStackRouteImport } from './routes/demos/renderer/multi-effect-stack'
import { Route as DemosRendererMemoryLeakRouteImport } from './routes/demos/renderer/memory-leak'
import { Route as DemosRendererEffectCollisionRouteImport } from './routes/demos/renderer/effect-collision'
import { Route as DemosNavigationTransitionAutoRouteImport } from './routes/demos/navigation/transition-auto'
import { Route as DemosNavigationTransitionRouteImport } from './routes/demos/navigation/transition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSurfacesRoute = DemosSurfacesRouteImport.update({
  id: '/demos/surfaces',
  path: '/demos/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosScrollableBasicRoute = DemosScrollableBasicRouteImport.update({
  id: '/demos/scrollable-basic',
  path: '/demos/scrollable-basic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosMotionBasicRoute = DemosMotionBasicRouteImport.update({
  id: '/demos/motion-basic',
  path: '/demos/motion-basic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosInputRoute = DemosInputRouteImport.update({
  id: '/demos/input',
  path: '/demos/input',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosDraggableBasicRoute = DemosDraggableBasicRouteImport.update({
  id: '/demos/draggable-basic',
  path: '/demos/draggable-basic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosCarouselRoute = DemosCarouselRouteImport.update({
  id: '/demos/carousel',
  path: '/demos/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosA11yRoute = DemosA11yRouteImport.update({
  id: '/demos/a11y',
  path: '/demos/a11y',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosScreenTransitionRoute = DemosScreenTransitionRouteImport.update({
  id: '/demos/screen/transition',
  path: '/demos/screen/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosScreenEffectStackRoute = DemosScreenEffectStackRouteImport.update({
  id: '/demos/screen/effect-stack',
  path: '/demos/screen/effect-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRendererQuadRenderingRoute =
  DemosRendererQuadRenderingRouteImport.update({
    id: '/demos/renderer/quad-rendering',
    path: '/demos/renderer/quad-rendering',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemosRendererMultiEffectStackRoute =
  DemosRendererMultiEffectStackRouteImport.update({
    id: '/demos/renderer/multi-effect-stack',
    path: '/demos/renderer/multi-effect-stack',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemosRendererMemoryLeakRoute = DemosRendererMemoryLeakRouteImport.update({
  id: '/demos/renderer/memory-leak',
  path: '/demos/renderer/memory-leak',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRendererEffectCollisionRoute =
  DemosRendererEffectCollisionRouteImport.update({
    id: '/demos/renderer/effect-collision',
    path: '/demos/renderer/effect-collision',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemosNavigationTransitionAutoRoute =
  DemosNavigationTransitionAutoRouteImport.update({
    id: '/demos/navigation/transition-auto',
    path: '/demos/navigation/transition-auto',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemosNavigationTransitionRoute =
  DemosNavigationTransitionRouteImport.update({
    id: '/demos/navigation/transition',
    path: '/demos/navigation/transition',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/a11y': typeof DemosA11yRoute
  '/demos/carousel': typeof DemosCarouselRoute
  '/demos/draggable-basic': typeof DemosDraggableBasicRoute
  '/demos/input': typeof DemosInputRoute
  '/demos/motion-basic': typeof DemosMotionBasicRoute
  '/demos/scrollable-basic': typeof DemosScrollableBasicRoute
  '/demos/surfaces': typeof DemosSurfacesRoute
  '/demos/navigation/transition': typeof DemosNavigationTransitionRoute
  '/demos/navigation/transition-auto': typeof DemosNavigationTransitionAutoRoute
  '/demos/renderer/effect-collision': typeof DemosRendererEffectCollisionRoute
  '/demos/renderer/memory-leak': typeof DemosRendererMemoryLeakRoute
  '/demos/renderer/multi-effect-stack': typeof DemosRendererMultiEffectStackRoute
  '/demos/renderer/quad-rendering': typeof DemosRendererQuadRenderingRoute
  '/demos/screen/effect-stack': typeof DemosScreenEffectStackRoute
  '/demos/screen/transition': typeof DemosScreenTransitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/a11y': typeof DemosA11yRoute
  '/demos/carousel': typeof DemosCarouselRoute
  '/demos/draggable-basic': typeof DemosDraggableBasicRoute
  '/demos/input': typeof DemosInputRoute
  '/demos/motion-basic': typeof DemosMotionBasicRoute
  '/demos/scrollable-basic': typeof DemosScrollableBasicRoute
  '/demos/surfaces': typeof DemosSurfacesRoute
  '/demos/navigation/transition': typeof DemosNavigationTransitionRoute
  '/demos/navigation/transition-auto': typeof DemosNavigationTransitionAutoRoute
  '/demos/renderer/effect-collision': typeof DemosRendererEffectCollisionRoute
  '/demos/renderer/memory-leak': typeof DemosRendererMemoryLeakRoute
  '/demos/renderer/multi-effect-stack': typeof DemosRendererMultiEffectStackRoute
  '/demos/renderer/quad-rendering': typeof DemosRendererQuadRenderingRoute
  '/demos/screen/effect-stack': typeof DemosScreenEffectStackRoute
  '/demos/screen/transition': typeof DemosScreenTransitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/a11y': typeof DemosA11yRoute
  '/demos/carousel': typeof DemosCarouselRoute
  '/demos/draggable-basic': typeof DemosDraggableBasicRoute
  '/demos/input': typeof DemosInputRoute
  '/demos/motion-basic': typeof DemosMotionBasicRoute
  '/demos/scrollable-basic': typeof DemosScrollableBasicRoute
  '/demos/surfaces': typeof DemosSurfacesRoute
  '/demos/navigation/transition': typeof DemosNavigationTransitionRoute
  '/demos/navigation/transition-auto': typeof DemosNavigationTransitionAutoRoute
  '/demos/renderer/effect-collision': typeof DemosRendererEffectCollisionRoute
  '/demos/renderer/memory-leak': typeof DemosRendererMemoryLeakRoute
  '/demos/renderer/multi-effect-stack': typeof DemosRendererMultiEffectStackRoute
  '/demos/renderer/quad-rendering': typeof DemosRendererQuadRenderingRoute
  '/demos/screen/effect-stack': typeof DemosScreenEffectStackRoute
  '/demos/screen/transition': typeof DemosScreenTransitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demos/a11y'
    | '/demos/carousel'
    | '/demos/draggable-basic'
    | '/demos/input'
    | '/demos/motion-basic'
    | '/demos/scrollable-basic'
    | '/demos/surfaces'
    | '/demos/navigation/transition'
    | '/demos/navigation/transition-auto'
    | '/demos/renderer/effect-collision'
    | '/demos/renderer/memory-leak'
    | '/demos/renderer/multi-effect-stack'
    | '/demos/renderer/quad-rendering'
    | '/demos/screen/effect-stack'
    | '/demos/screen/transition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demos/a11y'
    | '/demos/carousel'
    | '/demos/draggable-basic'
    | '/demos/input'
    | '/demos/motion-basic'
    | '/demos/scrollable-basic'
    | '/demos/surfaces'
    | '/demos/navigation/transition'
    | '/demos/navigation/transition-auto'
    | '/demos/renderer/effect-collision'
    | '/demos/renderer/memory-leak'
    | '/demos/renderer/multi-effect-stack'
    | '/demos/renderer/quad-rendering'
    | '/demos/screen/effect-stack'
    | '/demos/screen/transition'
  id:
    | '__root__'
    | '/'
    | '/demos/a11y'
    | '/demos/carousel'
    | '/demos/draggable-basic'
    | '/demos/input'
    | '/demos/motion-basic'
    | '/demos/scrollable-basic'
    | '/demos/surfaces'
    | '/demos/navigation/transition'
    | '/demos/navigation/transition-auto'
    | '/demos/renderer/effect-collision'
    | '/demos/renderer/memory-leak'
    | '/demos/renderer/multi-effect-stack'
    | '/demos/renderer/quad-rendering'
    | '/demos/screen/effect-stack'
    | '/demos/screen/transition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosA11yRoute: typeof DemosA11yRoute
  DemosCarouselRoute: typeof DemosCarouselRoute
  DemosDraggableBasicRoute: typeof DemosDraggableBasicRoute
  DemosInputRoute: typeof DemosInputRoute
  DemosMotionBasicRoute: typeof DemosMotionBasicRoute
  DemosScrollableBasicRoute: typeof DemosScrollableBasicRoute
  DemosSurfacesRoute: typeof DemosSurfacesRoute
  DemosNavigationTransitionRoute: typeof DemosNavigationTransitionRoute
  DemosNavigationTransitionAutoRoute: typeof DemosNavigationTransitionAutoRoute
  DemosRendererEffectCollisionRoute: typeof DemosRendererEffectCollisionRoute
  DemosRendererMemoryLeakRoute: typeof DemosRendererMemoryLeakRoute
  DemosRendererMultiEffectStackRoute: typeof DemosRendererMultiEffectStackRoute
  DemosRendererQuadRenderingRoute: typeof DemosRendererQuadRenderingRoute
  DemosScreenEffectStackRoute: typeof DemosScreenEffectStackRoute
  DemosScreenTransitionRoute: typeof DemosScreenTransitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/surfaces': {
      id: '/demos/surfaces'
      path: '/demos/surfaces'
      fullPath: '/demos/surfaces'
      preLoaderRoute: typeof DemosSurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/scrollable-basic': {
      id: '/demos/scrollable-basic'
      path: '/demos/scrollable-basic'
      fullPath: '/demos/scrollable-basic'
      preLoaderRoute: typeof DemosScrollableBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/motion-basic': {
      id: '/demos/motion-basic'
      path: '/demos/motion-basic'
      fullPath: '/demos/motion-basic'
      preLoaderRoute: typeof DemosMotionBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/input': {
      id: '/demos/input'
      path: '/demos/input'
      fullPath: '/demos/input'
      preLoaderRoute: typeof DemosInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/draggable-basic': {
      id: '/demos/draggable-basic'
      path: '/demos/draggable-basic'
      fullPath: '/demos/draggable-basic'
      preLoaderRoute: typeof DemosDraggableBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/carousel': {
      id: '/demos/carousel'
      path: '/demos/carousel'
      fullPath: '/demos/carousel'
      preLoaderRoute: typeof DemosCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/a11y': {
      id: '/demos/a11y'
      path: '/demos/a11y'
      fullPath: '/demos/a11y'
      preLoaderRoute: typeof DemosA11yRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/screen/transition': {
      id: '/demos/screen/transition'
      path: '/demos/screen/transition'
      fullPath: '/demos/screen/transition'
      preLoaderRoute: typeof DemosScreenTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/screen/effect-stack': {
      id: '/demos/screen/effect-stack'
      path: '/demos/screen/effect-stack'
      fullPath: '/demos/screen/effect-stack'
      preLoaderRoute: typeof DemosScreenEffectStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/renderer/quad-rendering': {
      id: '/demos/renderer/quad-rendering'
      path: '/demos/renderer/quad-rendering'
      fullPath: '/demos/renderer/quad-rendering'
      preLoaderRoute: typeof DemosRendererQuadRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/renderer/multi-effect-stack': {
      id: '/demos/renderer/multi-effect-stack'
      path: '/demos/renderer/multi-effect-stack'
      fullPath: '/demos/renderer/multi-effect-stack'
      preLoaderRoute: typeof DemosRendererMultiEffectStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/renderer/memory-leak': {
      id: '/demos/renderer/memory-leak'
      path: '/demos/renderer/memory-leak'
      fullPath: '/demos/renderer/memory-leak'
      preLoaderRoute: typeof DemosRendererMemoryLeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/renderer/effect-collision': {
      id: '/demos/renderer/effect-collision'
      path: '/demos/renderer/effect-collision'
      fullPath: '/demos/renderer/effect-collision'
      preLoaderRoute: typeof DemosRendererEffectCollisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/navigation/transition-auto': {
      id: '/demos/navigation/transition-auto'
      path: '/demos/navigation/transition-auto'
      fullPath: '/demos/navigation/transition-auto'
      preLoaderRoute: typeof DemosNavigationTransitionAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/navigation/transition': {
      id: '/demos/navigation/transition'
      path: '/demos/navigation/transition'
      fullPath: '/demos/navigation/transition'
      preLoaderRoute: typeof DemosNavigationTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosA11yRoute: DemosA11yRoute,
  DemosCarouselRoute: DemosCarouselRoute,
  DemosDraggableBasicRoute: DemosDraggableBasicRoute,
  DemosInputRoute: DemosInputRoute,
  DemosMotionBasicRoute: DemosMotionBasicRoute,
  DemosScrollableBasicRoute: DemosScrollableBasicRoute,
  DemosSurfacesRoute: DemosSurfacesRoute,
  DemosNavigationTransitionRoute: DemosNavigationTransitionRoute,
  DemosNavigationTransitionAutoRoute: DemosNavigationTransitionAutoRoute,
  DemosRendererEffectCollisionRoute: DemosRendererEffectCollisionRoute,
  DemosRendererMemoryLeakRoute: DemosRendererMemoryLeakRoute,
  DemosRendererMultiEffectStackRoute: DemosRendererMultiEffectStackRoute,
  DemosRendererQuadRenderingRoute: DemosRendererQuadRenderingRoute,
  DemosScreenEffectStackRoute: DemosScreenEffectStackRoute,
  DemosScreenTransitionRoute: DemosScreenTransitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
